USE [master]
GO

/****** Object:  Database [Chart]    Script Date: 06.12.2021 17:47:53 ******/
CREATE DATABASE [Chart]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Chart', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Chart.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Chart_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Chart_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Chart].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Chart] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Chart] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Chart] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Chart] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Chart] SET ARITHABORT OFF 
GO

ALTER DATABASE [Chart] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Chart] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Chart] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Chart] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Chart] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Chart] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Chart] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Chart] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Chart] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Chart] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Chart] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Chart] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Chart] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Chart] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Chart] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Chart] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Chart] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Chart] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Chart] SET  MULTI_USER 
GO

ALTER DATABASE [Chart] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Chart] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Chart] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Chart] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Chart] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Chart] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Chart] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Chart] SET  READ_WRITE 
GO

